### PR TITLE
Speed optimalization

### PR DESCRIPTION
**Pull request by Mattijah**
A bit cleaner and faster code. Speed improvement is somewhere between 20 to 40%. I say between because it depend on the format of messages. People that have busy TCP server which process for example JSON messages (as in my case) will notice some difference.

### CODE REVIEW

**Comment by pgte** [comment]
@Mattijah thanks!

Landed on v0.2.0.

**Comment by Mattijah** [comment]
@pgte I've tried to update the modul however npm downloads this release https://github.com/pgte/carrier/commit/0c32b096c2f284999dc20c220d9efe51188f88e1 (also v0.2.0)

**Comment by pgte** [comment]
Weird.

Anyway, released v0.2.1 from master, please check that one out.

**Comment by Mattijah** [comment]
@pgte It works correctly now. Thanks

**Pull request merged**
